# Generated by Django 6.0 on 2025-12-13 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField(max_length=500)),
                ('price', models.PositiveIntegerField()),
                ('slash_price', models.PositiveIntegerField(blank=True, null=True)),
                ('category', models.CharField(choices=[('appliance', 'Appliance'), ('electronics', 'Electronics'), ('phones', 'Phones'), ('fashion', 'Fashion'), ('beauty', 'Beauty'), ('computing', 'Computing')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
